name: 'Deploy Firebase Functions'
author: 'Andre Gallo <afgallo@gmail.com>, Adu Williams <aduwillie@gmail.com>, Chris Sankey'
description: 'A GitHub Action to deploy to Firebase Functions. It allows deployment of different targets i.e. development, production, etc.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'blue'
